-- ============================================================================
-- DEMO ONLY: spring.sql.init.mode=always runs this on every startup.
-- Drop order: children before parents (FK dependencies).
-- ============================================================================
DROP TABLE IF EXISTS inventory        CASCADE;
DROP TABLE IF EXISTS receipt_line     CASCADE;
DROP TABLE IF EXISTS receipt          CASCADE;
DROP TABLE IF EXISTS purchase_order_line CASCADE;
DROP TABLE IF EXISTS purchase_order   CASCADE;
DROP TABLE IF EXISTS location         CASCADE;
DROP TABLE IF EXISTS product          CASCADE;
DROP TABLE IF EXISTS vendor           CASCADE;
DROP TABLE IF EXISTS app_user         CASCADE;


-- ============================================================================
-- Dialect notes — this schema is PostgreSQL; what differs on DB2:
--   identity     GENERATED BY DEFAULT AS IDENTITY is SQL-standard — same on DB2.
--   BOOLEAN      DB2 needs 11.1+; older schemas use SMALLINT 0/1 or CHAR(1) 'Y'/'N'.
--   TIMESTAMPTZ  Does not exist on DB2 — use TIMESTAMP and store UTC.
--   updated_at   DB2 can auto-maintain it (GENERATED ALWAYS ... AS ROW CHANGE
--                TIMESTAMP); PostgreSQL needs a trigger or app discipline.
--   NUMERIC      DB2 usually spells it DECIMAL(12,2).
--   CHECK / FK   Identical syntax on both.
--   upsert       PostgreSQL: INSERT ... ON CONFLICT. DB2: MERGE.
--   now()        DB2: CURRENT TIMESTAMP. Intervals: CURRENT TIMESTAMP - 2 DAYS.
-- ============================================================================


-- User                 ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE app_user (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      varchar(50)  NOT NULL,
    last_name       varchar(50)  NOT NULL,
    password_hash   varchar(255) NOT NULL,
    email           varchar(255) NOT NULL UNIQUE,
    role            varchar(20)  NOT NULL
                    CONSTRAINT ck_user_role CHECK (role IN ('WAREHOUSE_CLERK','VIEWER'))
);

-- Vendor               ----------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE vendor (
    vendor_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- PK
    vendor_code     VARCHAR(20)  NOT NULL UNIQUE,                           -- vendor short name/code 
    name            VARCHAR(200) NOT NULL,                                  -- vendor full name
    active          BOOLEAN      NOT NULL DEFAULT TRUE                      -- Deactivate, never delete — old POs still reference this vendor.
);

-- Product              ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE product (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- PK
    sku             VARCHAR(40)  NOT NULL UNIQUE,                           -- Stock Keeping Unit, the warehouse business key 
    description     VARCHAR(255) NOT NULL,                                  -- Product Description
    unit_of_measure VARCHAR(10)  NOT NULL DEFAULT 'EA'                      -- EA -> Each || CS - > Case or boxes of many             
);

-- location of product  ----------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE location (
    location_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    --  You know
    location_code   VARCHAR(20) NOT NULL UNIQUE,                            --  DOCK-420, QC-69, A-67 (A for aisle)
    location_type   VARCHAR(20) NOT NULL DEFAULT 'STORAGE'                  
                    CONSTRAINT ck_location_type CHECK (location_type IN ('DOCK','STORAGE','QUARANTINE'))
    -- DOCK is where goods wait to be put away
    -- STORAGE is the place that it belongs to
    -- QUARANTINE is stock that exists but is not allowed to be used
);

-- Purchase Orders      ----------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE purchase_order (
    po_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- Yep
    po_number       VARCHAR(30) NOT NULL UNIQUE,                            -- business KEY
    vendor_id       BIGINT      NOT NULL REFERENCES vendor (vendor_id),     -- FK to vendor
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN'                     -- current status
                    CONSTRAINT ck_po_status CHECK (status IN ('OPEN','PARTIALLY_RECEIVED','CLOSED','CANCELLED')),
    
    order_date      DATE        NOT NULL,                                   -- When was it ordered
    expected_date   DATE,                                                   -- Expected to be received
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),                     -- When was it added to the database
    created_by      VARCHAR(50) NOT NULL,                                   -- Who created it
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),                     -- When was the last updated
    updated_by      VARCHAR(50) NOT NULL                                    -- Who made the last updated
          
);

-- Purchase Order Line  ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE purchase_order_line (
    po_line_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,            -- PK
    po_id               BIGINT NOT NULL REFERENCES purchase_order (po_id),              -- FK to purchase order
    line_number         INT    NOT NULL,                                                -- Position of the line within the order
    product_id          BIGINT NOT NULL REFERENCES product (product_id),                -- What product
    quantity_ordered    INT    NOT NULL                                                 -- How many were ordered > 0                     
                        CONSTRAINT ck_pol_qty_ordered CHECK (quantity_ordered > 0),
    quantity_received   INT    NOT NULL DEFAULT 0                                       -- Cached SUM(receipt_line.quantity_received) — GROSS, includes damaged.
                        CONSTRAINT ck_pol_qty_received CHECK (quantity_received >= 0),  -- Safe: single writer, same transaction as the receipt_line insert, atomic increment.
    unit_cost           NUMERIC(12,2)  NOT NULL DEFAULT 0,                              -- Price per unit
    CONSTRAINT uq_pol_po_line UNIQUE (po_id, line_number)                               -- Line numbers are unique within a PO 
);
CREATE INDEX ix_pol_po_id ON purchase_order_line (po_id);                               -- Index the FK

-- Receipts             ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE receipt (
    receipt_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- PK
    po_id             BIGINT      NOT NULL REFERENCES purchase_order (po_id),   -- order id
    received_by       VARCHAR(50) NOT NULL,                                     -- Person who signed for the goods.
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),                       -- Time received
    carrier_reference VARCHAR(50),                                              -- tracking / bill-of-lading number     
    notes             VARCHAR(500)                                              -- notes :3
);
CREATE INDEX ix_receipt_po_id ON receipt (po_id);                               -- Index the FK

-- Receipts Lines       ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE receipt_line (
    receipt_line_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                  -- PK
    receipt_id        BIGINT NOT NULL REFERENCES receipt (receipt_id),                      -- Receipt KFC (yes I am hungry)
    po_line_id        BIGINT NOT NULL REFERENCES purchase_order_line (po_line_id),          -- PURCHASE order LINE PK not PO for running total and over-receipt check.
    location_id       BIGINT NOT NULL REFERENCES location (location_id),                    -- Where the good units were put away.
    quantity_received INT    NOT NULL CONSTRAINT ck_rl_qty CHECK (quantity_received > 0),   -- Units that arrived on this line in this delivery — GROSS, includes damaged.
    quantity_damaged  INT    NOT NULL DEFAULT 0                                             -- Damaged units have to be less than the received units
        CONSTRAINT ck_rl_damaged CHECK (quantity_damaged >= 0 AND quantity_damaged <= quantity_received)
);
CREATE INDEX ix_rl_receipt_id ON receipt_line (receipt_id);                                 -- Index
CREATE INDEX ix_rl_po_line_id ON receipt_line (po_line_id);                                 -- Index

-- Inventory            ----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE inventory (
    inventory_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                               -- PK
    product_id       BIGINT NOT NULL REFERENCES product (product_id),                                   -- Product
    location_id      BIGINT NOT NULL REFERENCES location (location_id),                                 -- Location
    quantity_on_hand INT    NOT NULL DEFAULT 0 CONSTRAINT ck_inv_qty CHECK (quantity_on_hand >= 0),     -- Units at this location
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),                                                -- Last update
    CONSTRAINT uq_inventory_product_location UNIQUE (product_id, location_id)                           -- One stock row per product+location PAIR
);
